---
- hosts:  "{{ hostlist }}"
  remote_user: "{{ local_ssh_user }}"
  become: true
  environment:
    VAULT_USER: ansible-wireguard
    VAULT_PASSWORD: 123abc
    VAULT_AUTHTYPE: userpass
    VAULT_ADDR: 'http://192.168.100.20:8200/'
  tasks:
    - name: "Cheese"
      set_fact:
        provision_wg_server: True
        provision_wg_client: False
    - hashivault_list:
        mount_point: '/kv/wireguard-server'
#        key: centauriAlpha
        version: 2
      register: cheese
    - hashivault_read:
        mount_point: '/kv/wireguard-server'
#        key: centauriAlpha
        secret: terraOmega
        version: 2
      register: cheese



    - debug: msg="Known secrets are {{ cheese.value }}"

    - hashivault_read:
        mount_point: '/kv/wireguard-server'
        key: PrivateKey
        secret: terraDelta
        version: 2
      register: cheese
      ignore_errors: yes

    - debug: msg="Known secrets are {{ cheese.value }}"
      when: cheese.value is defined


    - set_fact:
        book: "{{lookup('hashivault', 'kv/wireguard-server/data/terraPhi',mount_point='/')}}"


    - debug: msg="Known secrets are {{ book.data }}"


    - name: "Dancing Bear"
      debug:
        msg: "{{ lookup('hashi_vault', 'secret=kv/wireguard-server/data/terraPhi auth_method=userpass username=ansible-wireguard password=123abc url=http://192.168.100.20:8200 validate_certs=no')}}"

#http://192.168.100.20:8200/v1/kv/wireguard-server/metadata/terraPhi
#http://192.168.100.20:8200/v1/kv/wireguard-server/data/terraPhi?version=1
