
---
- hosts: "{{ hostlist }}"
  remote_user: "{{ local_ssh_user }}"
  become: true
  roles:
    - role: mikolak-net.raspi_config
      raspi_config_replace_user:
         name: "{{ local_ssh_user }}"
    - role: "locales"
  tasks:
    - name: Install requisite packages (likely present)
      apt:
        name:
          - vim
          - acl
        state: present
        force_apt_get: yes
        cache_valid_time: 84600
    - name: Lock the Raspberry PI user
      user:
        name: pi
        password_lock: true
    - sysctl:
        name: net.core.default_qdisc
        value: fq
        state: present
    - sysctl:
        name: net.ipv4.tcp_congestion_control
        value: bbr
        state: present
    - sysctl:
        name:  net.core.rmem_max
        value: "{{ MaxExpectedPathBDP }}"
        state: present
    - sysctl:
        name: net.core.wmem_max
        value: "{{ MaxExpectedPathBDP }}"
        state: present
    - sysctl:
        name: net.ipv4.tcp_rmem
        value: "4096 87380 {{ MaxExpectedPathBDP }}"
        state: present
    - sysctl:
        name: net.ipv4.tcp_rmem
        value: "4096 87380 {{ MaxExpectedPathBDP }}"
        state: present
    - name: Remove existing symlink
      file:
        path: /etc/localtime
        state: absent
    - name: Add symlink
      file:
        src: "/usr/share/zoneinfo/{{Timezone}}"
        path: /etc/localtime
        owner: root
        group: root
        state: link
        mode: "0644"
    - name: Add symlink
      shell: "echo {{Timezone}} > /etc/timezone "
