---
- hosts:  "{{ hostlist }}"
  remote_user: "{{ local_ssh_user }}"
  become: true
  roles:
     - role: Stouts.hostname
     - role: msmtp
#     - role: ansible-role-pivpn
     - role: wifiClientSetup
  tasks:
     - name: Lock the Raspberry PI user
       user:
         name: pi
         password_lock: true
