
- hosts: hosts: "{{ansibleTarget}}"
  remote_user: "{{local_ssh_user}}"
  become: true
  roles:
     - role: Stouts.hostname
     - role: msmtp
     - role: ansible-role-pivpn
     - role: wifiSetup
     - role: role-install-gcloud
       become: yes
       become_user: "{{local_ssh_user}}"
     - role: phoneHome
       become: yes
       become_user: "{{local_ssh_user}}"
