---
- hosts:  "{{ hostlist }}"
  remote_user: "{{ local_ssh_user }}"
  become: true
  environment:
    VAULT_USER: "{{ vault_username }}"
    VAULT_PASSWORD: "{{ vault_password }}"
    VAULT_AUTHTYPE: userpass
    VAULT_ADDR: "{{ vault_address }}"
  pre_tasks:
    - name:
      set_fact:
        provision_wifi_server: True
    - name: DQ Check
      assert:
        that:
          - wifi_server_interface_name is defined
          - wifi_server_dhcp_range is defined
          - wifi_server_ssid is defined
          - wifi_server_wpa_type is defined
          - wifi_server_wpa_passkey is defined
          - wifi_server_setup_channel is defined
        fail_msg: "End of days man"


  roles:
     - role: wifiServerSetup
