---
- hosts:  "{{ hostlist }}"
  remote_user: "{{ local_ssh_user }}"
  become: true
  environment:
    VAULT_USER: "{{ vault_username }}"
    VAULT_PASSWORD: "{{ vault_password }}"
    VAULT_AUTHTYPE: userpass
    VAULT_ADDR: "{{ vault_address }}"
  pre_tasks:
     - name:
       set_fact:
         provision_wg_server: False
         provision_wg_client: True
  roles:
     - role: wireguardClientSetup
#     - role: role-install-gcloud
#       become: yes
#       become_user: "{{ local_ssh_user }}"
