---

- sysctl:
    name: net.ipv4.ip_forward
    value: 1
    state: present
- sysctl:
    name: net.core.default_qdisc
    value: fq
    state: present
- sysctl:
    name: net.ipv4.tcp_congestion_control
    value: bbr
    state: present

- name: Check if HostAPd directory exists
  stat:
    path: "/etc/hostapd/"
  register: wifiServerSetup_etc_hostapd

- name: Copy HostAPd  into place
  template:
    src: "{{ role_path }}/templates/etc/hostapd/hostapd.conf.j2"
    dest: "/etc/hostapd/hostapd.conf"
    mode: 0644
    owner: root
    group: root
  when: wifiServerSetup_etc_hostapd.stat.exists == True

- name: Copy dnsmasq config into place
  template:
    src: "{{ role_path }}/templates/etc/dnsmasq.conf.j2"
    dest: "/etc/dnsmasq.conf"
    mode: 0644
    owner: root
    group: root

- name: Copy Static IP for DHCPCD config into place
  template:
    src: "{{ role_path }}/templates/etc/dhcpcd.conf.j2"
    dest: "/etc/dhcpcd.conf"
    mode: 0644
    owner: root
    group: root


# Not needed if upstream router supports static NAT (ours does)
#- name: Enable NAT
#  iptables:
#    table: nat
#    chain: POSTROUTING
#    out_interface: eth0
#    source: "{{wifi_server_ip_range}}"
#    jump: MASQUERADE
#    comment: Redirect web traffic to port 8600
#  become: yes
