Vagrant.configure("2") do |config|
  config.vm.box = "fedora/34-cloud-base"
  config.vm.network "forwarded_port", guest: 9600, host: 9600
  config.vm.network "forwarded_port", guest: 9200, host: 9200
  config.vm.network "forwarded_port", guest: 5601, host: 5601

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end

  config.vm.provision "shell", inline: <<-SHELL

    yum install -y podman
    cat /etc/yum.repos.d/fedora-updates-testing.repo  | sed 's/enabled=0/enabled=1/' > /etc/yum.repos.d/fedora-updates-testing.repo
    yum upgrade podman
    groupadd -f -r podman


    #systemctl edit podman.socket
    mkdir -p /etc/systemd/system/podman.socket.d
    cat >/etc/systemd/system/podman.socket.d/override.conf <<EOF
[Socket]
SocketMode=0660
SocketUser=root
SocketGroup=podman
EOF
    systemctl daemon-reload
    echo "d /run/podman 0770 root podman" > /etc/tmpfiles.d/podman.conf
    sudo systemd-tmpfiles --create

    systemctl enable podman.socket
    systemctl start podman.socket

    usermod -aG podman $SUDO_USER
    sudo -u vagrant podman run -dt -p 9200:9200 -p 9600:9600 -e discovery.type=single-node --name es --restart always docker.io/amazon/opendistro-for-elasticsearch
    sudo -u vagrant podman run --replace -dt -p 5601:5601 -e ELASTICSEARCH_HOSTS=https://192.168.100.89:9200 --name kibana --restart always docker.io/amazon/opendistro-for-elasticsearch-kibana


  SHELL
end
