---
###############################################################################
################################# INSTALL #####################################
###############################################################################


# - debug: var=preexisting


- block:
  - name: "add {{ service_group }} system group"
    group:
        name: "{{ service_group }}"
        state: present
        system: true
  - name: "add {{service_user}} service account"
    user:
        name: "{{ service_user }}"
        comment: "{{ service_name }} Service Account"
        group: "{{ service_group }}"
        home: "{{ service_prefix }}"
        shell: /usr/sbin/nologin
        password_lock: true
  become: yes
  become_user: root
  tags: service_add_user
