---
###############################################################################
################################# INSTALL #####################################
###############################################################################

- stat:
    path: "{{ service_prefix }}"
  register: installed_ok
  tags:
    - service_systemd

- block:
  - name: create the tld paths
    file:
      path: "{{ service_prefix }}/"
      state: directory
      mode: 0755
      owner: "{{service_user}}"
      group: "{{service_group}}"
  - name: create the conf paths
    file:
      path: "{{ service_conf_dir }}"
      state: directory
      mode: 0755
      owner: "{{service_user}}"
      group: "{{service_group}}"
  - name: "create the {{ service_scripts_dir }} paths"
    file:
      path: "{{ service_scripts_dir }}"
      state: directory
      mode: 0755
      owner: "{{service_user}}"
      group: "{{service_group}}"

  - name: create the bin paths
    file:
      path: "{{ service_bin_dir }}"
      state: directory
      mode: 0755
      owner: "{{service_user}}"
      group: "{{service_group}}"
  - name: create the log paths
    file:
      path: "{{ service_log_dir }}"
      state: directory
      mode: 0755
      owner: "{{service_user}}"
      group: "{{service_group}}"

  when: installed_ok.stat.exists == true


###############################################################################
################################ FIXMEME - Download and Install####################################
###############################################################################


- name: Download the latest image
  debug:
   msg: "FIXME"

- name: Copy the binary into place
  copy:
   src: files/usr/bin/telegraf
   dest: "{{service_bin_dir}}/{{service_name}}"
   mode: '0755'
   owner: "{{service_user}}"
   group: "{{service_group}}"

#--name=service  --env-file=envfile -v ./etc-service/:/etc/service/:z -v ./etc-dnsmasq.d/:/etc/dnsmasq.d/:z --network=host service/service:latest

###############################################################################
################################ CONFIGURE ####################################
###############################################################################

- block:

  - name: Add envfile for {{service}}
    template:
      src: envfile.j2
      dest: "{{service_env_file}}"
      mode: 0600
      owner: "{{service_user}}"
      group: "{{service_group}}"


  - name: configure service for systemd
    template:
      src: templates/usr/lib/scripts/telegraf.service.j2
      dest: "{{ systemd_dir }}/{{service_name}}.service"
      mode: 0600
      owner: "{{service_user}}"
      group: "{{service_group}}"

    notify: reload systemd

  - name: enable service
    service:
      name: "{{ service_name }}"
      enabled: yes
      state: started

  become: yes
  become_user: "root"
  tags: service_systemd
