---
- name: restart vault
  become: yes
  become_user: root
  service:
    name: vault
    state: restarted

- name: reload systemd
  become: yes
  become_user: root
  command: systemctl daemon-reload
