---
- name: restart container
  become: yes
  become_user: "{{container_user}}"
  service:
    name: "{{ service_name }}"
    state: restarted

- name: restart unbound
  become: yes
  become_user: root
  command: systemctl restart unbound
