---
###############################################################################
################################# INSTALL #####################################
###############################################################################


# - debug: var=preexisting


- block:
  - name: add vault system group
    group:
        name: "{{ vault_group }}"
        state: present
        system: true 
  - name: configure vault for systemd
    user:
        name: "{{ vault_user }}"
        comment: "Vault Service Account"
        group: "{{ vault_group }}"
        shell: /usr/sbin/nologin
        password_lock: true
  become: yes
  become_user: root
  tags: vault_add_user
