---


- name: Check if data directory  exists
  stat:
    path: /var/data/iphistory/
  register: iphistory

- name: create data directory
  file:
    path: /var/data/
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
  become: yes
  become_user: root
  when:
    iphistory.stat.exists == False


- name: create data directory
  file:
    path: /var/data/iphistory/
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
  become: yes
  become_user: root
  when:
    iphistory.stat.exists == False

- name: Check if usrbin directory exists
  stat:
    path: "/home/{{ ansible_user }}/bin/"
  register: userbin

- name: create userbin directory if not exists
  file:
    path: "/home/{{ ansible_user }}/bin/"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
  when:
    userbin.stat.exists == False
  register: created_userbin



- name: Copy phoneHome scripts into place
  copy:
    src: "{{ item }}"
    dest: "/home/{{ ansible_user }}/bin/"
    mode: 0755
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  with_fileglob:
    - templates/phoneHome/bin/*
  when:
    userbin.stat.exists == True or created_userbin is defined


- name: Creates a cron file for phone home under {{ansible_user}}
  cron:
    name: phoneHome with latest ip daily
    special_time: daily
    user:  "{{ ansible_user }}"
    job: "/home/{{ansible_user}}/bin/iphistory.sh"
#    cron_file: iphistory_sh

- name: define our env
  cron:
    env: yes
    name:  LISTENPORT
    value: "{{ phoneHomePort }}"
#    cron_file: phoneHome_sh


- name: Creates a cron file for phone home under {{ansible_user}}
  cron:
    name: login to gcloud and wait for orders
    minute: 10,30,50
    user:  "{{ ansible_user }}"
    job: "/home/{{ ansible_user }}/bin/phoneHome.sh"
#    cron_file: phoneHome_sh

- name: Creates a cron file for phone home under {{ansible_user}}
  cron:
    name: login to terraAlpha and wait for orders
    minute: 10,30,50
    user:  "{{ ansible_user }}"
    job: "/home/{{ ansible_user }}/bin/phoneRealHome.sh"
#    cron_file: phoneHome_sh
