---
systemd_prefix: "container"
systemd_path: "/lib/systemd/system"
podman_local_path: "/usr/local/bin/podman"
container_prefix: "{{ container_system_prefix }}/{{ container_friendly_name }}/"
container_env_file: "{{ container_prefix }}/envfile.conf"
container_system_conf_dir: "{{ container_system_prefix }}/data/"
container_management_group: "systemd_container_manager"
container_management_polkit: "service-auth.pkla"
container_management_polkit_path: "/etc/polkit-1/localauthority/50-local.d"
