---
- name: "get file stat for {{ msmtp_mailrc_location }} to be able to perform check in the following task"
  stat:
    path: "{{ msmtp_mailrc_location }}"
  register: msmtp_mailrc
  tags:
    - msmtp_mailrc

- name: "Backup {{ msmtp_mailrc_location }} file if it exists"
  copy: src="{{ msmtp_mailrc_location }}" dest="{{ msmtp_mailrc_location }}.bak" remote_src=yes
#  remote_src: yes
  when: msmtp_mailrc.stat.exists
  tags:
    - msmtp_mailrc

- name: "Creating new {{ msmtp_mailrc_location }}"
  shell: printf "set sendmail='/usr/bin/msmtp'" > {{ msmtp_mailrc_location }}
  tags:
    - msmtp_mailrc

- name: "get file stat for {{msmtp_msmtprc_location}} to be able to perform check in the following task"
  stat:
    path: "{{ msmtp_msmtprc_location }}"
  register: msmtp_msmtprc
  tags:
    - msmtp_msmtprc

- name: "Backup {{msmtp_msmtprc_location}} file if it exists"
  copy: src="{{ msmtp_msmtprc_location }}" dest="{{ msmtp_msmtprc_location }}.bak" remote_src=yes
#  remote_src: yes
  when: msmtp_msmtprc.stat.exists
  tags:
    - msmtp_msmtprc

- name: Copy file with owner and permissions
  template:
    src: etc/msmtprc
    dest: "{{ msmtp_msmtprc_location }}"
    owner: "{{ msmtp_user }}"
    group: "{{ msmtp_group }}"
    mode: '0600'
  tags:
    - msmtp_msmtprc


- name: "Testing success"
  command:
    chdir: "/home/{{ msmtp_user }}"
    argv:
        - "/usr/bin/mail"
        - "-v"
        - "-s"
        - "'msmtp install success mail from {{msmtp_hostname}}'"
        - "nick.lange@gmail.com"
    stdin: "hello from {{msmtp_hostname}}"
  tags: msmtp_success
