---

- import_tasks: install.yml
  become: yes
  when: msmtp_enabled
  tags: msmtp_install,msmtp_setup

- import_tasks: configure_user.yml
  become: yes
  become_user: "{{ msmtp_user }}"
  when: msmtp_present
  tags: [msmtp_setup]
