---
vault_version: "1.5.3"
vault_checksum: "sha256:b51543ea3626322b12c593f2b3830c0b9cb7042d503df55229034cd297f98d13"
vault_install_path: /usr/local/vault/
vault_datacenter: dc1
vault_config_path: /usr/local/vault/etc/
vault_data_path: /usr/local/vault/data/
systemd_dir: /etc/systemd/system
vault_user: vault
vault_group: vault
