---

dependencies: []

galaxy_info:
  author: Nick Lange
  company: Private
  description: Installs MSTP and configures for the specified user for gmail
  license: MIT
  platforms:
  - name: Ubuntu
    versions:
    - all
  - name: Debian
    versions:
    - all
  - name: RedHat
    versions:
    - all
  - name: CentOS
    versions:
    - all
  categories:
  - system
