---
- hosts: "{{ hostlist | default('do_not_match_ever')}}"
  remote_user: "{{ local_ssh_user }}"
  become: true
  name: "Install Containerized home assistant as {{container_user}}"
  pre_tasks:
    - name: "Warm up"
      set_fact:
        container_user: "ha"
        container_group: "ha"
        ### FIXME ADD support for supplemental groups
        # May not need
        image_name: "ghcr.io/home-assistant/home-assistant:stable"
        container_friendly_name: "homeassistant"
        container_home_url: https://www.home-assistant.io/
      tags: key_vars
  tasks:
    - import_role:
        name: ansible-podman-systemd-generic
        tasks_from: "pre"
    - import_role:
        name: homeassistant.container
    - import_role:
        name: ansible-podman-systemd-generic
        tasks_from: "post"
