---
- hosts:  "{{ hostlist }}"
  remote_user: "{{ local_ssh_user }}"
  become: true
  name: "Install Containerized homebride as {{hb_user}}"
  roles:
    - { role: homebridge.container, become: yes }
