---
- hosts: "{{ hostlist | default('do_not_match_ever')}}"
  remote_user: "{{ local_ssh_user }}"
  become: true
  tasks:
    - name: Install requisite packages (likely present)
      apt:
        name:
          - tcpdump
          - jq
          - podman
        state: present
        force_apt_get: yes
        cache_valid_time: 84600
    - name: Make sure we have a 'wheel' group
      group:
        name: wheel
        state: present

    - name: Add Kenta
      user:
        name: kenta
        comment: Kenta
        groups: wheel
        shell: /bin/bash
        password_lock: true
    - name: Set authorized key taken from file
      authorized_key:
        user: kenta
        state: present
        key: "{{ kenta_ssh_key }}"
    - name: bash - Fix user systemd, XDG For interactive and non-interactive shells
      ansible.builtin.lineinfile:
        path: "/etc/bash.bashrc"
        regexp: .*XDG_RUNTIME_DIR.*
        state: present
        insertafter: EOF
        line: if [ $(id -u) != 0 ]; then declare -x XDG_RUNTIME_DIR=/var/run/user/$(id -u)/; fi
    - name: Fix user systemd, XDG For interactive and non-interactive shells
      ansible.builtin.lineinfile:
        path: "/etc/profile"
        regexp: .*XDG_RUNTIME_DIR.*
        state: present
        insertafter: EOF
        line: if [ $(id -u) != 0 ]; then export XDG_RUNTIME_DIR=/var/run/user/$(id -u)/; fi
#        git config --global alias.co checkout
#        git config --global alias.br branch
#        git config --global alias.ci commit
#        git config --global alias.st status
