
---
- hosts: "{{ hostlist | default('do_not_match_ever')}}"
  remote_user: "{{ local_ssh_user }}"
  become: true
  roles:
    - role: "fix_sudoers"
      raspi_config_replace_user:
         name: "{{ local_ssh_user }}"
         path_to_ssh_key: "/Users/{{ local_ssh_user }}/.ssh/id_rsa_stronger.pub"
    - role: "locales"
  tasks:
    - name: Install requisite packages (likely present)
      apt:
        name:
          - vim
          - acl
          - ca-certificates
        state: present
        force_apt_get: yes
        cache_valid_time: 84600
    - name: Remove existing symlink
      file:
        path: /etc/localtime
        state: absent
    - name: Add symlink
      file:
        src: "/usr/share/zoneinfo/{{Timezone}}"
        path: /etc/localtime
        owner: root
        group: root
        state: link
        mode: "0644"
    - name: Add symlink
      shell: "echo {{Timezone}} > /etc/timezone "
    - name: Lock the Raspberry PI user
      user:
        name: pi
        password_lock: true
