---
- hosts: "{{ hostlist | default('do_not_match_ever')}}"
  remote_user: "{{ local_ssh_user }}"
  become: true
  pre_tasks:
    - set_fact:
        msmtp_fresh: true
  roles:
     - role: msmtp
#     - role: ansible-role-pivpn
