---
- hosts: "{{ hostlist | default('do_not_match_ever')}}"
  remote_user: "{{ local_ssh_user }}"
  become: true
  roles:
    - role: ansible-phoneHome
      become: yes
      become_user: "{{ local_ssh_user }}"
      when: phoneHomePort is defined
