---
- hosts: "{{ hostlist | default('do_not_match_ever')}}"
  remote_user: "{{ local_ssh_user }}"
  become: true
  name: Install Containerized Pihole as pihole
  pre_tasks:
    - name: "Warm up"
      set_fact:
        # May not need
        image_name: "docker.io/pihole/pihole:latest"
        container_friendly_name: "pihole"
        container_user: "pihole"
        container_group: "pihole"

        container_home_url: https://pi-hole.net/
      tags: key_vars
  tasks:
    - import_role:
        name: ansible-podman-systemd-generic
        tasks_from: "pre"
    - import_role:
        name: pihole.container
    - import_role:
        name: ansible-podman-systemd-generic
        tasks_from: "post"
