---
- hosts: "{{ hostlist | default('do_not_match_ever')}}"
  remote_user: "{{ local_ssh_user }}"
  become: true
  pre_tasks:
    - name: "Warm up"
      set_fact:
        container_user: "telegraf"
        container_group: "telegraf"
        # May not need
        image_name: "docker.io/library/telegraf:latest"
        container_friendly_name: "telegraf"
        container_home_url: https://github.com/influxdata/telegraf
      tags: key_vars
  tasks:
     - import_role:
        name: ansible-podman-systemd-generic
        tasks_from: "pre"
     - import_role:
        name: telegraf-container-service
     - import_role:
        name: ansible-podman-systemd-generic
        tasks_from: "post"
