---
- hosts: "{{ hostlist | default('do_not_match_ever')}}"
  remote_user: "{{ local_ssh_user }}"
  become: true
  name: DNS Subdomain Refresh
  tasks:
    - name: "Refresh DNS Subdomains"
      import_role:
        name: pihole.container
        tasks_from: "unbound_localzone"
