---
- hosts: "{{ hostlist | default('do_not_match_ever')}}"
  remote_user: "{{ local_ssh_user }}"
  become: true
  environment:
    VAULT_USER: "{{ vault_username }}"
    VAULT_PASSWORD: "{{ vault_password }}"
    VAULT_AUTHTYPE: userpass
    VAULT_ADDR: "{{ vault_address }}"
  pre_tasks:
    - name:
      set_fact:
        provision_wg_server: False
        provision_wg_client: False
        add_wg_client: True
    - name: DQ Check
      assert:
        that:
          - wireguard_client_server_endpoint is defined
          - wireguard_client_ip is defined
        fail_msg: "End of days man"


  roles:
     - role: wireguardServerSetup
