---
###############################################################################
################################# INSTALL #####################################
###############################################################################


- block:
  - name: "add systemd-container-manager system group"
    group:
        name: "{{ container_management_group }}"
        state: present
        system: true

  - name: "add {{ container_group }} system group"
    group:
        name: "{{ container_group }}"
        state: present
        system: true
  - name: "add {{container_user}} service account"
    user:
        name: "{{ container_user }}"
        comment: "{{ container_friendly_name }} Service Account"
        group: "{{ container_group }}"
        home: "{{ container_prefix }}"
        shell: /usr/sbin/nologin
        password_lock: true
        groups: "{{ container_management_group }}"
  - name: snag the userid
    shell: "id -u {{ container_user }}"
    register: container_user_pid
    tags: container_systemd_start
  - debug:
      msg: "{{container_user}} uid is {{container_user_pid.stdout}}"
    tags: container_systemd_start
  - name: enable linger
    shell: "XDG_RUNTIME_DIR=/var/run/user/{{ container_user_pid.stdout }} loginctl enable-linger {{ container_user }}"
    args:
      executable: /bin/bash
  become: true
  become_user: root
  when: container_user != "root"
  tags: container_add_user
